django/whish_list/apps/wishlist/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^login$', views.login, name="login"),
    url(r'^register$', views.register, name="register"),
    url(r'^dashboard$', views.dashboard, name="dashboard"),
    url(r'^wish_items/create$', views.create, name="create"),
    url(r'^wish_items/new_item$', views.new, name="new_item"),
    url(r'^delete/(?P<wish_id>\d+)$', views.delete, name="delete"),
    url(r'^remove/(?P<wish_id>\d+)$', views.remove, name="remove"),
    url(r'^addto/(?P<wish_id>\d+)$', views.addto, name="addto"),
]

django/whish_list/whish_list/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.wishlist.urls', namespace="wishlist")),
]

django/whish_list/apps/wishlist/models.py
from __future__ import unicode_literals
import re, bcrypt
from django.db import models

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+.[a-zA-Z]+$')

class UserManager(models.Manager):
    def register(self, formData):
        #store possbile failed validations
        errors = []

        if len(formData['first_name']) < 3:
            errors.append("First name must be at least 2 characters long!")
        if len(formData['last_name']) < 3:
            errors.append("Last name must be at least 2 characters long!")
        if not len(formData['email']):
            errors.append("email is required")
        if not EMAIL_REGEX.match(formData['email']):
            errors.append("email is not valid")
        if len(formData['password']) < 8:
            errors.append("Password must be 8 char long!")
        if not formData['password'] == formData['confirm']:
            errors.append("Passwords must match")
        user = User.objects.filter(email= formData['email'])

        if user:
            errors.append("Email must be unique!")

        response = {}

        if errors:
            response['status'] = False
            response['errors'] = errors
            return response
        else:
            hashedPw = bcrypt.hashpw(formData['password'].encode(), bcrypt.gensalt())
            user = self.create(first_name=formData['first_name'], last_name=formData['last_name'], email=formData['email'], password=hashedPw)
            response['status'] = True
            response['user'] = user
            return response

    def login(self, formData):
        response = {}
        errors = []

        if not len(formData['email']):
            errors.append("email is required")
        if not EMAIL_REGEX.match(formData['email']):
            errors.append("email is not valid")
        if len(formData['password']) < 8:
            errors.append("Password must be 8 char long!")

        else:
            user = User.objects.filter(email=formData['email'])
            if user:
                if bcrypt.checkpw(formData['password'].encode(), user[0].password.encode()):
                    response['user'] = user[0]
                    response['status'] = True
                    return response
                else:
                    response['status'] = False
                    response['errors'] = "Invalid Password/Email Combo!"
                    return response
        response['status'] = False
        response['errors'] = errors
        return response

class WishManager(models.Manager):
    def newWish(self, formData, user_id):
        user = User.objects.get(id=user_id)
        response = {}
        if len(formData['wish_item']) > 3:
            wish = self.create(wish_name=formData['wish_item'])
            item = Wish.objects.get(id=wish.id)
            item.wisher.add(user)
            response['status'] = True
            return response
        else:
            response['status'] = False
            response['errors'] = "Must be longer than 3 char!!"
        return response
    def delete(self, wish_id):
        Wish.objects.get(id=wish_id).delete()
        return "Deleted"

    def remove(self, wish_id):
        Wish.objects.get(id=wish_id).delete()
        return "deleted"

    def addTo(self, wish_id, user_id):
        wish = Wish.objects.get(id=wish_id)
        user = User.objects.get(id=user_id)
        wish.wishes.add(user)
class User(models.Model):
    first_name = models.CharField(max_length=38)
    last_name = models.CharField(max_length= 38)
    email = models.CharField(max_length= 25)
    password = models.CharField(max_length= 100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

class Wish(models.Model):
    wish_name = models.CharField(max_length=40)
    wisher = models.ManyToManyField(User, related_name="wishers")
    wishes = models.ManyToManyField(User, related_name="wishes")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = WishManager()

django/whish_list/apps/wishlist/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User, Wish

def index(request):
    return render(request, ('wishlist/index.html'))

def register(request):
    if request.method == "POST":
        response = User.objects.register(request.POST)
        if response['status']:
            request.session['name'] = response['user'].first_name
            request.session['id'] = response['user'].id
            return redirect('wishlist:dashboard')
        else:
            errors = response['errors']
            for error in errors:
                messages.error(request, error)
            return redirect('wishlist:index')

def login (request):
    if request.method == "POST":
        response = User.objects.login(request.POST)
        if response['status']:
            request.session['name'] = response['user'].first_name
            request.session['id'] = response['user'].id
            return redirect('wishlist:dashboard')
        else:
            messages.error(request, response['errors'])
            return redirect('wishlist:index')

def dashboard(request):
    user = User.objects.get(id=request.session['id'])
    context = {
    "users" : User.objects.all(),
    "wishes" : Wish.objects.all(),
    "current": user
    }
    return render(request, ('wishlist/dashboard.html'), context)

def create(request):
    return render(request, ("wishlist/create.html"))

def new(request):
    user = request.session['id']
    response = Wish.objects.newWish(request.POST, user)
    if response:
        return redirect('wishlist:dashboard')
        messages.errors = response['errors']
    return redirect("wishlist:create")


def delete(request, wish_id):
    Wish.objects.delete(wish_id)
    return redirect("wishlist:dashboard")

def remove(request, wish_id):
    user_id = request.session['id']
    Wish.objects.remove(wish_user)
    return redirect("wishlist:dashboard")

def addto(request, wish_id):
    user_id = request.session['id']
    response = Wish.objects.addTo(wish_id, user_id)

    return redirect("wishlist:dashboard")

django/whish_list/apps/wishlist/templates/wishlist/create.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Create</title>
  </head>
  <body>
    <h1>Create New Wish Item</h1>
    <form class="" action="{% url 'wishlist:new_item'%}" method="post">
      {% csrf_token %}
      <input type="text" name="wish_item" value="">
      <input type="submit" name="submit" value="Create Item">
    </form>
  </body>
</html>

django/whish_list/apps/wishlist/templates/wishlist/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello!</title>
  </head>
  <body>
    <h1>Welcome</h1>
    <h1>{{request.session.name}}</h1>
    <h3>Here is your wishlist</h3>
    <table>
      <thead>
        <th>Item</th>
        <th>Added By</th>
        <th>Date Added</th>
        <th>Action</th>
      </thead>
      {% for value in current.wishes.all %}
      <tbody>
          <td>{{value.wish_name}}</td>
          <td>{{value.first_name}}</td>
          <td>{{value.created_at}}</td>
          {%if value.id != request.session.id%}
            <td><a href="{% url 'wishlist:remove' value.id %}">Remove From My List</a></td>
          {%else%}
            <td><a href="{% url 'wishlist:delete' value.id %}">Delete MY CREATED item</a></td>
          {%endif%}
      </tbody>
      {% endfor %}
    </table>

    <h3>Other Wishlist</h3>

    <table>
      <thead>
        <th>Item</th>
        <th>Added By</th>
        <th>Date Added</th>
        <th>Action</th>
        {% for wish in wishes %}
        {% for value in wish.wisher.all %}
          <tbody>
            <td><p>{{wish.wish_name}}</p></td>
            <td><p>{{value.first_name}}</p><td>
            <td><p>{{wish.created_at}}</p></td>
            {%if value.id == request.session.id%}
              <td><a href="{% url 'wishlist:delete' wish.id %}">Delete</a></td>
              <td><td><a href="{% url 'wishlist:addto' wish.id %}">Add to MY list</a></td></td>
            {%else%}
              <td><td><a href="{% url 'wishlist:addto' wish.id %}">Add to MY list</a></td></td>
            {%endif%}
          </tbody>
          {% endfor %}
        {% endfor %}
      </thead>
    </table>
    <a href="{% url 'wishlist:create'%}">Add Item</a>
  </body>
</html>

django/whish_list/apps/wishlist/templates/wishlist/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Welcome to Wish List</title>
  </head>
  <body>
    <h1>Welcome!</h1>
    <h3>Please Login or Register to Continue</h3>
    <form class="" action="/register" method="post">
  {% csrf_token %}
  <br>
  <label for="first_name">First Name:</label>
  <br>
  <input type="text" name="first_name" value="">
  <br>
  <br>
  <label for="last_name">Last Name:</label>
  <br>
  <input type="text" name="last_name" value="">
  <br>
  <br>
  <label for="email">Email:</label>
  <br>
  <input type="email" name="email" value="">
  <br>
  <br>
  <label for="password">Password:</label>
  <br>
  <input type="password" name="password" value="">
  <br>
  <br>
  <label for="confirm">Confirm:</label>
  <br>
  <input type="Password" name="confirm" value="">
  <br>
  <br>
  <input type="submit" name="submit" value="submit">
</form>
{%if messages%}
  {% for message in messages %}
    <p>{{message}}</p>
  {% endfor %}
{%endif%}
<br>
<h3>Login</h3>
<form class="" action="/login" method="post">
  {% csrf_token %}
  <br>
  <label for="email">Email:</label>
  <br>
  <input type="email" name="email" value="">
  <br>
  <br>
  <label for="password">Password:</label>
  <br>
  <input type="password" name="password" value="">
  <br>
  <br>
  <input type="submit" name="submit" value="submit">
</form>

    </form>
  </body>
</html>