django/appointments/appointments/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^main/', include('apps.appointment.urls', namespace = "users")),
]

django/appointments/apps/appointment/urls.py
from django.conf.urls import url, include
from . import views
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register$', views.register, name="register"),
    url(r'^appointments$', views.success, name="success"),
    url(r'^createNew$', views.createNew, name="createNew"),
    url(r'^edit/(?P<apt_id>\d+)$', views.edit, name="edit"),
    url(r'^editPage/(?P<apt_id>\d+)$', views.editPage, name="editPage"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^delete/(?P<apt_id>\d+)$', views.delete, name="delete"),
]

django/appointments/apps/appointment/models.py
from __future__ import unicode_literals
import re, bcrypt
from django.db import models
import datetime

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+.[a-zA-Z]+$')

class UserManager(models.Manager):
    def register(self, formData):
        #store possbile failed validations
        errors = []
        dob = formData['dob']
        dateParts = dob.split("-")
        print dateParts
        if len(formData['first_name']) < 3:
            errors.append("First name must be at least 2 characters long!")
        if len(formData['last_name']) < 3:
            errors.append("Last name must be at least 2 characters long!")
        if not len(formData['email']):
            errors.append("email is required")
        if not EMAIL_REGEX.match(formData['email']):
            errors.append("email is not valid")
        if len(formData['password']) < 8:
            errors.append("Password must be 8 char long!")
        if not formData['password'] == formData['confirm']:
            errors.append("Passwords must match")
        if len(dateParts) < 3:
            errors.append("Not a valid birthday")
        user = User.objects.filter(email= formData['email'])

        if user:
            errors.append("Email must be unique!")

        response = {}

        if errors:
            response['status'] = False
            response['errors'] = errors
            return response
        else:
            hashedPw = bcrypt.hashpw(formData['password'].encode(), bcrypt.gensalt())
            user = self.create(first_name=formData['first_name'], last_name=formData['last_name'], email=formData['email'], password=hashedPw, dob=(formData['dob']))
            response['status'] = True
            response['user'] = user
            return response

    def login(self, formData):
        response = {}
        errors = []

        if not len(formData['email']):
            errors.append("email is required")
        if not EMAIL_REGEX.match(formData['email']):
            errors.append("email is not valid")
        if len(formData['password']) < 8:
            errors.append("Password must be 8 char long!")

        else:
            user = User.objects.filter(email=formData['email'])
            if user:
                if bcrypt.checkpw(formData['password'].encode(), user[0].password.encode()):
                    response['user'] = user[0]
                    response['status'] = True
                    return response
                else:
                    response['status'] = False
                    response['errors'] = "Invalid Password/Email Combo!"
                    return response
        response['status'] = False
        response['errors'] = errors
        return response

class AppointmentManager(models.Manager):
    def createNew(self, formData, user_id):
        response = {}
        errors = []
        if len(formData['tasks']) < 3:
            errors.append("Must be a task longer than 3 char!")
        if len(formData['date']) < 3:
            errors.append("Must be a task longer than 3 char!")
        if errors:
            response['errors'] = errors
            response['status'] = False
            return response
        else:
            dateParts = formData['date'].split("-")
            creator = User.objects.get(id=user_id)
            apt = self.create(tasks=formData['tasks'], user=creator, status="pending", date=formData['date'], time=formData['time'])
            task = Appointment.objects.get(id=apt.id)
            response['status'] = True
            return response

    def edit(self, apt_id, formData):
        Appointment.objects.filter(id=apt_id).update(tasks=formData['tasks'], status=formData['select'], date=formData['date'], time= formData['time'])

    def deleteApt(self, apt_id):
        Appointment.objects.get(id=apt_id).delete()


class User(models.Model):
    first_name = models.CharField(max_length=38)
    last_name = models.CharField(max_length= 38)
    email = models.CharField(max_length= 25)
    password = models.CharField(max_length= 100)
    dob = models.DateTimeField(auto_now_add=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

class Appointment(models.Model):
    tasks = models.CharField(max_length=40)
    user = models.ForeignKey(User, related_name="user_tasks")
    status = models.CharField(max_length=40)
    date = models.DateField(auto_now=False)
    time = models.TimeField(auto_now=False)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = AppointmentManager()

django/appointments/apps/appointment/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User, Appointment
import datetime

def index(request):
    return render(request, ('appointment/index.html'))

def success(request):
    now =  datetime.date.today()
    context = {
    'now' : datetime.date.today(),
    'current': User.objects.get(id=request.session['id']),
    'appt': Appointment.objects.all(),
    'today' : Appointment.objects.filter(date=now),
    }
    return render(request, ('appointment/appointments.html'), context)

def createNew(request):
    user_id = request.session['id']
    response = Appointment.objects.createNew(request.POST, user_id)
    if response['status']:
        return redirect("users:success")
    else:
        errors = response['errors']
        for error in errors:
            messages.error(request, error)
        return redirect("users:success")
def editPage(request, apt_id):
    context = {
    'apt' : Appointment.objects.get(id=apt_id)
    }
    return render(request, ("appointment/edit.html"), context)

def edit(request, apt_id):
    Appointment.objects.edit(apt_id, request.POST)
    return redirect("users:success")

def register(request):
    if request.method == "POST":
        response = User.objects.register(request.POST)
        if response['status']:
            request.session['name'] = response['user'].first_name
            request.session['id'] = response['user'].id
            return redirect('users:success')
        else:
            errors = response['errors']
            for error in errors:
                messages.error(request, error)
            return redirect('users:index')

def login(request):
    if request.method == "POST":
        response = User.objects.login(request.POST)
        if response['status']:
            request.session['name'] = response['user'].first_name
            request.session['id'] = response['user'].id
            return redirect('users:succss')
        else:
            errors = response['errors']
            for error in errors:
                messages.error(request, error)
            return redirect('users:index')

def delete(request, apt_id):
    Appointment.objects.deleteApt(apt_id)
    return redirect('users:success')
def logout(request):
    request.session.clear()
    return redirect("users:index")

django/appointments/apps/appointment/templates/appointment/appointments.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello</title>
  </head>
  <body>
    <a href="{% url 'users:logout'%}">Logout</a>
    <h1>Hello, {{request.session.name}}</h1>
    <h3>Here are your appointments for today - {{now}}.</h3>
    <table>
      <thead>
        <th>Tasks</th>
        <th>Time</th>
        <th>Status</th>
        <th>action</th>
      </thead>
    {% for value in today %}
      <tbody>
          <td>{{value.tasks}}</td>
          <td>{{value.time}}</td>
          <td>{{value.status}}</td>
          {%if value.status == "pending"%}
            <td><a href="{% url 'users:editPage' value.id %}">Edit</a> | <a href="{% url 'users:delete' value.id %}">Delete</a></td>
          {%else%}
            <td><a href="{% url 'users:editPage' value.id %}">Edit</a></td>
          {%endif%}
      </tbody>
    {% endfor %}
    </table>
    <h3>Add Appointment</h3>
    {%if messages%}
      {% for message in messages %}
        <p>{{message}}</p>
      {% endfor %}
    {%endif%}
    <form class="" action="{% url 'users:createNew' %}" method="post">
      {% csrf_token %}
      <label for="date">Date</label>
      <input type="date" name="date" value="">
      <label for="time">Time</label>
      <input type="time" name="time" value="">
      <label for="tasks">Task</label>
      <input type="text" name="tasks" value="">
      <input type="submit" name="submit" value="Add">
    </form>
    {{current.dob.date}}
    <table>
      <thead>
        <th>Tasks</th>
        <th>Time</th>
        <th>Status</th>
        <th>action</th>
      </thead>
    {% for value in appt %}
      <tbody>
          <td>{{value.tasks}}</td>
          <td>{{value.date}}</td>
          <td>{{value.status}}</td>
          {%if value.status == "pending"%}
            <td><a href="{% url 'users:editPage' value.id %}">Edit</a> | <a href="{% url 'users:delete' value.id %}">Delete</a></td>
          {%else%}
            <td><a href="{% url 'users:editPage' value.id %}">Edit</a></td>
          {%endif%}
      </tbody>
    {% endfor %}
    </table>
  </body>
</html>

django/appointments/apps/appointment/templates/appointment/edit.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit</title>
    <style media="screen">
      td, th{
        border : 2px solid #333;
        padding : 5px;
      }
    </style>
  </head>
  <body>
    <a href="{% url 'users:success'%}">Dashboard</a> | <a href="{% url 'users:logout'%}">Logout</a>
    <h3>You are currently editing: "{{apt.tasks}}"</h1>
    <table>
      <thead>
        <th>Current Task</th>
        <th>Current Status</th>
        <th>Change Status</th>
      </thead>
      <tbody>
        <td>{{apt.tasks}}</td>
        <td>{{apt.status}}</td>
        <td>  <form class="" action="{% url 'users:edit' apt.id %}" method="post">
                {% csrf_token %}
                <input type="text" name="tasks" value="{{apt.tasks}}">
                <select class="" name="select">
                  <option value="pending">Pending</option>
                  <option value="done">Done</option>
                  <option value="missed">missed</option>
                </select>
                <input type="date" name="date" value={{apt.date}}>
                <input type="time" name="time" value={{apt.time}}>

                <input type="submit" name="" value="Update">
            </form>
        </td>
      </tbody>
    </table>
  </body>
</html>

django/appointments/apps/appointment/templates/appointment/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Welcome to Wish List</title>
  </head>
  <body>
    <h1>Welcome!</h1>
    <h3>Please Login or Register to Continue</h3>
    <form class="" action="{% url 'users:register'%}" method="post">
  {% csrf_token %}
  <br>
  <label for="first_name">First Name:</label>
  <br>
  <input type="text" name="first_name" value="">
  <br>
  <br>
  <label for="last_name">Last Name:</label>
  <br>
  <input type="text" name="last_name" value="">
  <br>
  <br>
  <label for="email">Email:</label>
  <br>
  <input type="email" name="email" value="">
  <br>
  <br>
  <label for="password">Password:</label>
  <br>
  <input type="password" name="password" value="">
  <br>
  <br>
  <label for="confirm">Confirm:</label>
  <br>
  <input type="Password" name="confirm" value="">
  <br>
  <br>
  <label for="dob">Date of Birth:</label>
  <br>
  <input type="date" name="dob" value="">
  <br>
  <br>
  <input type="submit" name="submit" value="submit">
</form>
{%if messages%}
  {% for message in messages %}
    <p>{{message}}</p>
  {% endfor %}
{%endif%}
<br>
<h3>Login</h3>
<form class="" action="/login" method="post">
  {% csrf_token %}
  <br>
  <label for="email">Email:</label>
  <br>
  <input type="email" name="email" value="">
  <br>
  <br>
  <label for="password">Password:</label>
  <br>
  <input type="password" name="password" value="">
  <br>
  <br>
  <input type="submit" name="submit" value="submit">
</form>

    </form>
  </body>
</html>